<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="style/css/app.css">
        <link rel="stylesheet" type="text/css" href="style/css/index.css">
        <title>Calendex - ce mois</title>
    </head>
    <body>
        <?php

        function dbg($var) {
            echo '<pre>';
            var_dump($var);
            echo '</pre>';
        }

        function afficheMois($mois) {
            // génère la variable infos et la variable jours
            extract($mois);
            ?>
            <div class="mois-in">
                <div class="titremois">
                    <?= "{$infos['nom_mois']} {$infos['annee']}"; ?>
                </div>
                <div class="jours">
    <?php foreach ($jours as $idJour => $jour): ?>
                        <table class="jour <?= ($jour['WE'])?'we':'';?> <?= ($jour['aujourdhui'])?'aujourdhui':'';?>">
                            <tr>
                                <td class="abrnomjour"><?= $jour['abr_jour']; ?></td>
                                <td class="numjour"><?= $jour['jour']; ?></td>
                                <td class="event">
                                    <ul class="event-perp">
                                        <?php foreach ($jour['eventPermanent'] as $eventPermanent): ?>
                                            <li><?= $eventPermanent; ?></li>
                                        <?php endforeach; ?>
                                    </ul>
                                    <ul class="event-norm">
                                        <?php foreach ($jour['eventNormal'] as $eventNormal): ?>
                                            <li><?= $eventNormal; ?></li>
        <?php endforeach; ?>
                                    </ul>
                                </td>
                                <td class="za<?= ($jour['vacancesZA']) ? ' vac' : ''; ?>">&nbsp;</td>
                                <td class="zb<?= ($jour['vacancesZB']) ? ' vac' : ''; ?>">&nbsp;</td>
                                <td class="zc<?= ($jour['vacancesZC']) ? ' vac' : ''; ?>">&nbsp;</td>
                                <td class="btnadd"><a href="" class="btn btnadd-perp">+</a>
                                    <a href="" class="btn btnadd-norm">+</a></td>
                            </tr>
                        </table>
            <?php endforeach; ?>
                </div>
            </div>
            <?php
        }
        ?>
        <div id="maste">
            <div id="header">
                <h1>
                    <span class="logo"></span>
                    <span class="titre"></span>
                </h1>
                <div class="btnnav">

                </div>
            </div>
            <div id="content">
                <div class="mois"><div class="masc"></div>
                    <?php afficheMois($mois_precedant); ?>
                </div>
                <div class="mois">
                    <?php afficheMois($mois_en_cours); ?>
                </div>
                <div class="mois"><div class="masc"></div>
<?php afficheMois($mois_suivant); ?>
                </div>	
            </div>
        </div>
    </body>
</html>
